openapi: 3.0.3
info:
  title: Retro Video Game Exchange
  description: API that allows users to exchange video games.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: temp Local development

paths:
  /games:
    post:
      summary: Add a new game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '201':
          description: Game created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Invalid request

  /games/{gameId}:
    put:
      summary: Replace a game
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '200':
          description: Game updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: Game not found

    patch:
      summary: Update a game
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '200':
          description: Game updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: Game not found

    delete:
      summary: Delete a game
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Game deleted
        '404':
          description: Game not found

  /users:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid request

  /users/{userId}:
    put:
      summary: Replace user information
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

    patch:
      summary: Update user information
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found

    delete:
      summary: Delete a user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found

components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        platform:
          type: string
        condition:
          type: string

    UserCreate:
      type: object
      required:
        - name
        - email
        - password
        - streetAddress
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        streetAddress:
          type: string

    UserUpdate:
      type: object
      properties:
        name:
          type: string
        streetAddress:
          type: string

    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        streetAddress:
          type: string
          

